// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.VisionBot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveBaseLeftMain;
    public static WPI_TalonSRX driveBaseLeftSecond;
    public static WPI_TalonSRX driveBaseRightMain;
    public static WPI_TalonSRX driveBaseRightSecond;
    public static DifferentialDrive driveBaseRobotDrive41;
    public static SpeedControllerGroup leftSpeed;
    public static SpeedControllerGroup rightSpeed;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static ADXRS450_Gyro gyro;
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseLeftMain = new WPI_TalonSRX(1);
        driveBaseLeftSecond = new WPI_TalonSRX(2);
        driveBaseRightMain = new WPI_TalonSRX(4);
        driveBaseRightSecond = new WPI_TalonSRX(3);
        
        leftSpeed = new SpeedControllerGroup(driveBaseLeftMain, driveBaseLeftSecond);
        rightSpeed = new SpeedControllerGroup(driveBaseRightMain, driveBaseRightSecond);

        driveBaseRobotDrive41 = new DifferentialDrive(leftSpeed, rightSpeed);
        System.out.println("Init");
        driveBaseRobotDrive41.setSafetyEnabled(true);
        driveBaseRobotDrive41.setExpiration(0.1);
        driveBaseRobotDrive41.setMaxOutput(1.0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        gyro = new ADXRS450_Gyro();
        
        SmartDashboard.putData("Left Main", driveBaseLeftMain);
        SmartDashboard.putData("Left Second", driveBaseLeftSecond);  
    }
}
