// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4089.VisionBot;

import org.usfirst.frc4089.VisionBot.subsystems.Navigation;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.sensors.PigeonIMU;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import stealth_libraries.Encoder;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  public static WPI_TalonSRX leftMotor1SpeedCpmtroler;
  public static WPI_TalonSRX leftMotor2SpeedCpmtroler;
  public static WPI_TalonSRX rightMotor1SpeedCpmtroler;
  public static WPI_TalonSRX rightMotor2SpeedCpmtroler;
  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  private static final double kVoltsPerDegreePerSecond = 0.0128;
  /*
   * Talon SRX/ Victor SPX will supported multiple (cascaded) PID loops. For now
   * we just want the primary one.
   */
  public static final int kPIDLoopIdx = 0;

  /*
   * set to zero to skip waiting for confirmation, set to nonzero to wait and
   * report to DS if action fails.
   */
  public static final int kTimeoutMs = 10;
  public static PigeonIMU pigeonIMU;

  public static NetworkTable netTable;
  public static NetworkTable piTable;

  public static Encoder leftEncoder;
  public static Encoder rightEncoder;

  public static void init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    leftMotor1SpeedCpmtroler = new WPI_TalonSRX(Constants.kLeftMotor1SpeedControl);
    leftMotor2SpeedCpmtroler = new WPI_TalonSRX(Constants.kLeftMotor2SpeedControl);
    rightMotor1SpeedCpmtroler = new WPI_TalonSRX(Constants.kRightMotor1SpeedControl);
    rightMotor2SpeedCpmtroler = new WPI_TalonSRX(Constants.kRightMotor2SpeedControl);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    leftEncoder = new Encoder(leftMotor1SpeedCpmtroler);
    rightEncoder = new Encoder(rightMotor1SpeedCpmtroler);
    leftEncoder.SetTicksPerRev(Constants.kEncoderPulsePerRev);
    leftEncoder.SetRevToInches(Constants.kWheelCirc);
    rightEncoder.SetTicksPerRev(Constants.kEncoderPulsePerRev);
    rightEncoder.SetRevToInches(Constants.kWheelCirc);

    pigeonIMU = new PigeonIMU(leftMotor2SpeedCpmtroler);
    pigeonIMU.setFusedHeading(0.0, 10);

    netTable = NetworkTable.getTable("FRCRobot");
    piTable = NetworkTable.getTable("piBlob0");

    SetUpTalon(leftMotor1SpeedCpmtroler);
    SetUpTalon(rightMotor1SpeedCpmtroler);
    leftMotor2SpeedCpmtroler.set(ControlMode.Follower, Constants.kLeftMotor1SpeedControl);
    rightMotor2SpeedCpmtroler.set(ControlMode.Follower, Constants.kRightMotor1SpeedControl);
    rightMotor1SpeedCpmtroler.setInverted(true);
    rightMotor2SpeedCpmtroler.setInverted(true);

    Navigation.getInstance().setRobotWidth(28.0);
    Navigation.getInstance().setNewPose(0, 0, 0);
  }

  static void SetUpTalon(WPI_TalonSRX talon) {
    talon.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, kTimeoutMs);
    talon.setSensorPhase(true);

    /* set the peak and nominal outputs, 12V means full */
    talon.configNominalOutputForward(0, kTimeoutMs);
    talon.configNominalOutputReverse(0, kTimeoutMs);
    talon.configPeakOutputForward(1, kTimeoutMs);
    talon.configPeakOutputReverse(-1, kTimeoutMs);

    /* set closed loop gains in slot0 */
    talon.config_kF(kPIDLoopIdx, 0.34, kTimeoutMs);
    talon.config_kP(kPIDLoopIdx, 0.2, kTimeoutMs);
    talon.config_kI(kPIDLoopIdx, 0, kTimeoutMs);
    talon.config_kD(kPIDLoopIdx, 0, kTimeoutMs);

    talon.setSafetyEnabled(true);
    talon.setExpiration(kTimeoutMs);
  }

  static public double returnRawGyro() {
    double[] rawGyro = new double[3];
    RobotMap.pigeonIMU.getRawGyro(rawGyro);
    return rawGyro[Constants.kGyroZ];
  }

  static public double reutrnGyro() {
    return returnRawGyro() * Constants.kGyroGain;
  }
}
